---
name: bdm_voxel_builder

channels:
  - conda-forge
  - nodefaults

dependencies:
  - click
  - compas=>2.3.0
  - compas_fab
  - compas_viewer
  - invoke
  - matplotlib
  - numpy
  - openvdb>=11.0.0
  - pypcd4
  - pytest
  - python>=3.11,<4
  - ruff
  - setuptools
