---
name: bdm_voxel_builder

channels:
  - conda-forge
  - nodefaults

dependencies:
  - click
  - compas=>2.4.1
  - compas_fab
  - compas_viewer
  - compas_rrc
  - invoke
  - matplotlib
  - more-itertools
  - numpy
  - openvdb>=11.0.0
  - pypcd4
  - pytest
  - python>=3.11,<4
  - requests
  - ruff
  - setuptools
