name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: ./environment.yml
      - name: pytest
        shell: pwsh
        run: invoke install
      - name: pytest
        shell: pwsh
        run: invoke test
