name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
defaults:
  run:
    shell: pwsh
jobs:
  test:
    name: Test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        python-version: ["3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Cache conda
        uses: actions/cache@v4
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@835234971496cad1653abb28a638a281cf32541f # v3.2.0
        with:
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}
          environment-file: ./environment.yml
          use-only-tar-bz2: false

      - name: install local package
        run: invoke install

      - name: check
        run: invoke check
        continue-on-error: true

      - name: test
        run: invoke test
